sudo: false

dist: trusty

language: c

compiler:
  - gcc

cache:
  apt: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update -q
    fi
    
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update
        brew install mfem
    fi

script: make && make test
