export TGT=pdfLgvn
export MESH=1

export LOG= -t #-v $(TGT).log
export ADDITIONAL_NABLA_FILES = #spectrum.n
export ADDITIONAL_DEFINES = #-DNB_PARTICLES=200000

include ~/nabla/build/tests/Makefile.nabla.lambda
