TGT=p12D

MESH_X = 10
MESH_Y = 10
MESH_Z = 1

#SIMD = std
#PARALLEL = seq
#LOG = -t -v $(TGT).log 

ADDITIONAL_NABLA_FILES=p1ExactSol.n p1Boundaries.n p1TimeStep.n p1Init.n p1GeomQuads.n

include ./Makefile.nabla.lambda
