        .section ".rodata"
        .global knDbg_h
        .global knMsh_c
        .global knMth_h
        
        .global knStdReal_h
        .global knStdReal3_h
        .global knStdInteger_h
        .global knStdTernary_h
        .global knStdGather_h
        .global knStdScatter_h
        .global knStdOStream_h

        .global knSseReal_h
        .global knSseReal3_h
        .global knSseInteger_h
        .global knSseTernary_h
        .global knSseGather_h
        .global knSseScatter_h
        .global knSseOStream_h

        .global knAvxReal_h
        .global knAvxReal3_h
        .global knAvxInteger_h
        .global knAvxTernary_h
        .global knAvxGather_h
        .global knAvxScatter_h
        .global knAvxOStream_h
        
        .global knMicReal_h
        .global knMicReal3_h
        .global knMicInteger_h
        .global knMicTernary_h
        .global knMicGather_h
        .global knMicScatter_h
        .global knMicOStream_h
        

        
knDbg_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knDbg.h"
        .byte 0
knMsh_c: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMsh.c"
        .byte 0
knMth_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMth.h"
        .byte 0


        
knStdReal_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdReal.h"
        .byte 0
knStdReal3_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdReal3.h"
        .byte 0
knStdInteger_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdInteger.h"
        .byte 0
knStdTernary_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdTernary.h"
        .byte 0
knStdGather_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdGather.h"
        .byte 0
knStdScatter_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdScatter.h"
        .byte 0
knStdOStream_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knStdOStream.h"
        .byte 0


        
knSseReal_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseReal.h"
        .byte 0
knSseReal3_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseReal3.h"
        .byte 0
knSseInteger_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseInteger.h"
        .byte 0
knSseTernary_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseTernary.h"
        .byte 0
knSseGather_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseGather.h"
        .byte 0
knSseScatter_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseScatter.h"
        .byte 0
knSseOStream_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knSseOStream.h"
        .byte 0


        
knAvxReal_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxReal.h"
        .byte 0
knAvxReal3_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxReal3.h"
        .byte 0
knAvxInteger_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxInteger.h"
        .byte 0
knAvxTernary_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxTernary.h"
        .byte 0
knAvxGather_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxGather.h"
        .byte 0
knAvxScatter_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxScatter.h"
        .byte 0
knAvxOStream_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knAvxOStream.h"
        .byte 0


        
knMicReal_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicReal.h"
        .byte 0
knMicReal3_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicReal3.h"
        .byte 0
knMicInteger_h:
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicInteger.h"
        .byte 0
knMicTernary_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicTernary.h"
        .byte 0
knMicGather_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicGather.h"
        .byte 0
knMicScatter_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicScatter.h"
        .byte 0
knMicOStream_h: 
	     .incbin "CMakeFiles/nabla.dir/backends/okina/knMicOStream.h"
        .byte 0

