TGT=nahea

DFT_PATH = /cea/S/home/s3/camierjs/cea/lab/lucas/nlucas
EXTRA_LIBS=-L$(DFT_PATH) -lllt -Wl,-rpath,$(DFT_PATH)

include ~/cea/arcane/nabla/bin/Makefile.$(shell cea_os).local
#include ~/cea/arcane/nabla/bin/Makefile.$(shell cea_os)
