dirige -c -f /cea/S/home/s3/camierjs/cea/arcane/nabla/nahea.llt/nahea.${MSUB_REQID}
#MSUB -r nahea
#MSUB -s arcane
#MSUB -x
#MSUB -M 2000
#MSUB -c 1
#MSUB -n 1
#MSUB -N 1
##MSUB -T 3600
#MSUB -q batch
export ARCANE_PARALLEL_SERVICE=Mpi
cd /cea/S/home/s3/camierjs/cea/arcane/nabla/nahea.llt
/usr/local/sr/bin/cea_mprun -n 1 ./nahea ./nahea.arc
#/usr/local/sr/bin/cea_mprun -n 1 ./nahea -arcane_opt continue ./nahea.arc
