include(${NABLA_SOURCE_DIR}/cmake/CMakeTPL.txt)

#info("ARCANE_ROOT set to ${ARCANE_ROOT}")

find_path(ARCANE_INCLUDE_DIR arcane_config.h ${ARCANE_ROOT}/include)
#info("ARCANE_INCLUDE_DIR set to ${VT100_FG_RED}${ARCANE_INCLUDE_DIR}${VT100_RESET}")

if(ARCANE_INCLUDE_DIR)
  set(ARCANE_FOUND "YES")
endif(ARCANE_INCLUDE_DIR)

if(ARCANE_FOUND)
  info("\t${VT100_FG_MAGENTA}ARCANE${VT100_RESET} has been found in ${VT100_BOLD}${ARCANE_ROOT}${VT100_RESET}")
endif(ARCANE_FOUND)
