include(${NABLA_SOURCE_DIR}/cmake/CMakeTPL.txt)

find_path(LEGION_ROOT_PATH include/legion/legion.h ${LEGION_ROOT})
find_path(LEGION_LANGUAGE language/regent.py ${LEGION_ROOT})
find_path(LEGION_BINDING bindings/terra/liblegion_terra.so ${LEGION_ROOT})
find_path(LEGION_RUNTIME runtime/runtime.mk ${LEGION_ROOT})

if (LEGION_ROOT_PATH AND LEGION_LANGUAGE AND LEGION_BINDING AND LEGION_RUNTIME)
  set(LEGION_FOUND true)
endif(LEGION_ROOT_PATH AND LEGION_LANGUAGE AND LEGION_BINDING AND LEGION_RUNTIME)
  
if (LEGION_FOUND)
  info("\t${VT100_FG_MAGENTA}LEGION${VT100_RESET} has been found in ${VT100_BOLD}${LEGION_ROOT_PATH}${VT100_RESET}")
endif(LEGION_FOUND)
  