include(${NABLA_SOURCE_DIR}/cmake/CMakeTPL.txt)

FIND_LIBRARY(ICET_CORE_LIBRARY IceTCore ${ICET_ROOT}/lib)
FIND_LIBRARY(ICET_MPI_LIBRARY IceTMPI ${ICET_ROOT}/lib)
FIND_LIBRARY(ICET_GL_LIBRARY IceTGL ${ICET_ROOT}/lib)

#MESSAGE(STATUS "ICET_CORE_LIBRARY = ${ICET_CORE_LIBRARY}")
#MESSAGE(STATUS "ICET_MPI_LIBRARY = ${ICET_MPI_LIBRARY}")
#MESSAGE(STATUS "ICET_GL_LIBRARY = ${ICET_GL_LIBRARY}")

FIND_PATH(ICET_INCLUDE_DIR IceT.h ${ICET_ROOT}/include)

#MESSAGE(STATUS "ICET_INCLUDE_DIR = ${ICET_INCLUDE_DIR}")
 
SET(ICET_FOUND "NO" )
IF(ICET_INCLUDE_DIR)
  IF(ICET_CORE_LIBRARY AND ICET_GL_LIBRARY AND ICET_MPI_LIBRARY)
    SET( ICET_FOUND "YES" )
    SET( ICET_LIBRARIES "${ICET_MPI_LIBRARY} ${ICET_GL_LIBRARY} ${ICET_CORE_LIBRARY}")
    SET( ICET_INCLUDE_DIRS ${ICET_INCLUDE_DIR})
  ENDIF(ICET_CORE_LIBRARY AND ICET_GL_LIBRARY AND ICET_MPI_LIBRARY)
ENDIF(ICET_INCLUDE_DIR)

if(ICET_FOUND)
  info("\t${VT100_FG_MAGENTA}IceT${VT100_RESET} has been found in ${VT100_BOLD}${ICET_ROOT}${VT100_RESET}")
  info("\t${VT100_FG_MAGENTA}IceT${VT100_RESET} libraries are ${VT100_BOLD}${ICET_LIBRARIES}${VT100_RESET}")
endif(ICET_FOUND)
