include(${NABLA_SOURCE_DIR}/cmake/CMakeTPL.txt)

find_path(MFEM_INCLUDE_PATH mfem.hpp ${MFEM_ROOT_PATH})
info("${VT100_FG_MAGENTA}MFEM${VT100_RESET} set to ${VT100_BOLD}${MFEM_INCLUDE_PATH}${VT100_RESET}")

if(MFEM_INCLUDE_PATH)
  set(MFEM_FOUND "YES")
endif(MFEM_INCLUDE_PATH)
