export TGT=glace
#LOG=-v $(TGT).log
ADDITIONAL_NABLA_FILES = glaceGeomQuads.n glaceGeomTriangles.n glaceGeomHexa.n glaceBoundaries.n
#include ../bin/Makefile.$(shell cea_os).local
include ../bin/Makefile.$(shell cea_os)
